Update how to component
alercebroker/Watchlist-Frontend pull request #57
Opened 2024-06-19 13:51 UTC by Demurest

## Summary of the changes
- Se actualizó el componente HowTo con nuevas instrucciones, que se han incorporado en el archivo SetFilters.vue.
- Se adaptó el componente CreateWatchlist.vue para crear watchlist a partir de csv sin la columna filtro.

## Observations

## If the change is BREAKING, please give more details about the breaking changes

#### Components that need updates and steps to follow

## About this PR:

- [ X] You added the necessary documentation for the team to understand your work.
- [ ] You linked this PR to the corresponding issue or user story.
- [ ] Your changes fulfill the Definition of Done of the issue or user story.
- [ ] Your changes were tested with manual testing before being submitted.
- [ ] Your changes were tested with automatic unit tests.
- [ ] Your changes were tested with automatic integration tests.

## Screensshots

2024-06-19 15:41 UTC, HectorxH requested changes

2024-06-19 15:41 UTC, HectorxH commented on src/ui/components/watchlist/CardFilter.vue
> +          ¿Are you sure you want to change all the filters in the watchlist?
```suggestion
          Are you sure you want to change all the filters in the watchlist?
```

'¿' no se usa en ingles

2024-06-19 15:41 UTC, HectorxH commented on src/ui/components/watchlist/CreateWatchlist.vue
> +
Este console log esta de mas, se deberia borrar

2024-06-21 19:46 UTC, Demurest commented on src/ui/components/watchlist/CreateWatchlist.vue
> +
Cambios listos.

2024-06-21 20:07 UTC, merged